apiVersion: v1
kind: ConfigMap
metadata: { name: mosquitto-conf, namespace: psbench }
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: mosquitto, namespace: psbench }
spec:
  replicas: 1
  selector: { matchLabels: { app: mosquitto } }
  template:
    metadata: { labels: { app: mosquitto } }
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: cfg
          mountPath: /mosquitto/config
      volumes:
      - name: cfg
        configMap:
          name: mosquitto-conf
---
apiVersion: v1
kind: Service
metadata: { name: mosquitto, namespace: psbench }
spec:
  selector: { app: mosquitto }
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883

